[package]
name = "sysy_compiler"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
lazy_static = "1.5.0"
lalrpop-util = { version = "0.19.7", features = ["lexer"] }
